# ===========================
#  Namespace (/** es todo)
# ===========================
/**:
  # ===================
  #     NODO
  # ===================
  ros__parameters:
    # ----- ME00_camera PARAMS -----
    autorun: true
    topics: ["/chatter", "/chatter2"]